apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-visualizer-app-deployment
  labels:
    app: the-visualizer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: the-visualizer-app
  template:
    metadata:
      labels:
        app: the-visualizer-app
    spec:
      containers:
      - name: the-visualizer-app-container
        image: the-visualizer-app-docker:tag
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: the-visualizer-app-service
spec:
  selector:
    app: the-visualizer-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
